### ISSUE TITLE
How do you get to run?

### ISSUE THREAD

**Issue by daMogli** [dnlcrl/PyScholar#1] opened 2015-11-07 06:46 UTC
I cloned your git repo, can't get it to run.
In .../Pyscholar/src running:
python pyscholar.py -c 1 --author "albert einstein" --phrase "quantum theory"

resulting in:

> ~/PyScholar/src/pyscholar.py(216)main()
> -> print e
> (Pdb)

**Comment by dnlcrl** [comment] 2015-11-07 09:13
Hi daMogli, thanks for pointing out the issue, it was caused by a wrong default parameter, it should be fixed now.
Can you pull and confirm?

Thanks.

**Closed as completed** 2015-11-09 10:12 UTC
Labels: question
